/** Demo profile — dipakai saat Supabase belum dikonfigurasi */
export const MOCK_PROFILE = {
  id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  username: 'cobazeus',
  display_name: 'Coba Zeus',
  bio: 'Streamer FPS kompetitif. Main VALORANT & CS2 setiap malam jam 8! GG EZ no re.',
  min_donation: 10000,
  avatar_url: null,
}

const now = Date.now()

/** Demo donations — dipakai saat Supabase belum dikonfigurasi */
export const MOCK_DONATIONS = [
  {
    id: 'd1',
    sender_name: 'BudiGaming',
    amount: 50000,
    amount_received: 48000,
    message: 'Ayo win rank ini bro! GG!',
    status: 'success',
    created_at: new Date(now - 2 * 60_000).toISOString(),
  },
  {
    id: 'd2',
    sender_name: 'SitiStream',
    amount: 25000,
    amount_received: 24000,
    message: 'Mantap streamnya, keep it up!',
    status: 'success',
    created_at: new Date(now - 15 * 60_000).toISOString(),
  },
  {
    id: 'd3',
    sender_name: 'Anonim',
    amount: 100000,
    amount_received: 96000,
    message: 'Gas terus kontennya, sultan hadir!',
    status: 'success',
    created_at: new Date(now - 45 * 60_000).toISOString(),
  },
  {
    id: 'd4',
    sender_name: 'GamerPro99',
    amount: 10000,
    amount_received: 9600,
    message: '',
    status: 'pending',
    created_at: new Date(now - 2 * 3_600_000).toISOString(),
  },
  {
    id: 'd5',
    sender_name: 'NyawerFan',
    amount: 75000,
    amount_received: 72000,
    message: 'Semangat terus!',
    status: 'failed',
    created_at: new Date(now - 3 * 3_600_000).toISOString(),
  },
  {
    id: 'd6',
    sender_name: 'ReksaGunawan',
    amount: 20000,
    amount_received: 19200,
    message: 'Comeback dong!',
    status: 'success',
    created_at: new Date(now - 5 * 3_600_000).toISOString(),
  },
  {
    id: 'd7',
    sender_name: 'DewiCantik',
    amount: 150000,
    amount_received: 144000,
    message: 'Sultan masuk, jangan kalah!',
    status: 'success',
    created_at: new Date(now - 8 * 3_600_000).toISOString(),
  },
  {
    id: 'd8',
    sender_name: 'AgungPro',
    amount: 30000,
    amount_received: 28800,
    message: 'Wkwkwk clutch dong',
    status: 'success',
    created_at: new Date(now - 12 * 3_600_000).toISOString(),
  },
  {
    id: 'd9',
    sender_name: 'Anonim',
    amount: 50000,
    amount_received: 48000,
    message: 'Potongan 4% emang murah banget!',
    status: 'success',
    created_at: new Date(now - 18 * 3_600_000).toISOString(),
  },
  {
    id: 'd10',
    sender_name: 'FitraFPS',
    amount: 200000,
    amount_received: 192000,
    message: 'Legendnya hadir! Jangan kalah ya!',
    status: 'success',
    created_at: new Date(now - 24 * 3_600_000).toISOString(),
  },
]
